Kiboko\Component\SocialNetwork\Model\Member:
  type: entity
  repositoryClass: Kiboko\Component\SocialNetwork\Repository\UserRepository
  table: kiboko_social_member
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    createdAt:
      type: datetime
      column: created_at
      gedmo:
        timestampable:
          on: create
    updatedAt:
      type: datetime
      column: updated_at
      gedmo:
        timestampable:
          on: update
  oneToOne:
    avatar:
      targetEntity: Kiboko\Component\SocialNetwork\Model\Attachment
      joinColumn:
        name: avatar_attachment_id
        referencedColumnName: id
    banner:
      targetEntity: Kiboko\Component\SocialNetwork\Model\Attachment
      joinColumn:
        name: banner_attachment_id
        referencedColumnName: id
  oneToMany:
    messages:
      targetEntity: Kiboko\Component\SocialNetwork\Model\MessageRecipient
      mappedBy: target
