Kiboko\Component\SocialNetwork\Model\MessageRecipient:
  type: entity
  table: kiboko_social_message_recipient
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    wasRead:
      type: boolean
      column: was_read
      options:
        default: 0
    createdAt:
      type: datetime
      column: created_at
      gedmo:
        timestampable:
          on: create
    updatedAt:
      type: datetime
      column: updated_at
      gedmo:
        timestampable:
          on: update
  manyToOne:
    message:
      targetEntity: Kiboko\Component\SocialNetwork\Model\Message
      inversedBy: target
      joinColumn:
        name: message_id
        referencedColumnName: id
        onDelete: cascade
    recipient:
      targetEntity: Kiboko\Component\SocialNetwork\Model\Member
      inversedBy: messages
      joinColumn:
        name: member_id
        referencedColumnName: id
        onDelete: cascade
