Kiboko\Component\SocialNetwork\Model\Message:
  type: entity
  repositoryClass: Kiboko\Component\SocialNetwork\Repository\MessageRepository
  table: kiboko_social_message
  fields:
    id:
      type: integer
      id: true
      column: id
      generator:
        strategy: AUTO
    subject:
      type: string
      length: 255
      notBlank: true
      column: subject
    content:
      type: text
      column: content
    allowAnswer:
      type: boolean
      column: allow_answer
    messageType:
      type: string
      length: 90
      nullable: true
      column: message_type
    createdAt:
      type: datetime
      column: created_at
      gedmo:
        timestampable:
          on: create
    updatedAt:
      type: datetime
      column: updated_at
      gedmo:
        timestampable:
          on: update
  manyToOne:
    parent:
      targetEntity: Kiboko\Component\SocialNetwork\Model\Message
      inversedBy: children
      joinColumn:
        name: parent_id
        referencedColumnName: id
        onDelete: cascade
    sender:
      targetEntity: Kiboko\Component\SocialNetwork\Model\User
      inversedBy: sender
      joinColumn:
        name: sender_id
        referencedColumnName: id
        onDelete: set null
  oneToMany:
    recipient:
      targetEntity: Kiboko\Component\SocialNetwork\Model\MessageRecipient
      mappedBy: messages
    children:
      targetEntity: Kiboko\Component\SocialNetwork\Model\Message
      mappedBy: parent
